name: rseed
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  dio: ^5.9.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  sqlite3_flutter_libs: ^0.5.30
  path: ^1.9.1
  dartz: ^0.10.1
  equatable: ^2.0.8
  internet_connection_checker: ^3.0.1
  google_fonts: ^8.0.2
  shared_preferences: ^2.5.5
  cached_network_image: ^3.4.1
  pretty_dio_logger: ^1.4.0
  flutter_svg: ^2.2.4
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.5
  easy_localization: ^3.0.8
  animate_do: ^4.2.0
  lottie: ^3.3.0
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  bloc: ^9.2.0
  mobile_scanner: ^7.2.0
  fl_chart: ^0.70.2
  excel: ^4.0.5
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^10.1.4
  animated_bottom_navigation_bar: ^1.4.0
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# إعدادات الأيقونة (مهم تكون خارج dev_dependencies)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_logo.png
    - assets/images/
    - assets/lang/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300