// File generated by FlutterFire CLI.
// ignore_for_file: type=lint, uri_does_not_exist
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7-Mb0dwkru_H7IuWJ3A74y5mINU2p7Ek',
    appId: '1:761135292455:web:34b98665790abdd03e6e02',
    messagingSenderId: '761135292455',
    projectId: 'rseed-770db',
    authDomain: 'rseed-770db.firebaseapp.com',
    storageBucket: 'rseed-770db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpcZPoYqszhKxyn4WnbpncrXiQeM1s2l8',
    appId: '1:761135292455:android:9c4cf4a32ec379a23e6e02',
    messagingSenderId: '761135292455',
    projectId: 'rseed-770db',
    storageBucket: 'rseed-770db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfT2vDFih4IjlhDyYZFTp3be2KZvB8Kco',
    appId: '1:761135292455:ios:aa11457896debbdd3e6e02',
    messagingSenderId: '761135292455',
    projectId: 'rseed-770db',
    storageBucket: 'rseed-770db.firebasestorage.app',
    iosBundleId: 'com.example.rseed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfT2vDFih4IjlhDyYZFTp3be2KZvB8Kco',
    appId: '1:761135292455:ios:aa11457896debbdd3e6e02',
    messagingSenderId: '761135292455',
    projectId: 'rseed-770db',
    storageBucket: 'rseed-770db.firebasestorage.app',
    iosBundleId: 'com.example.rseed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7-Mb0dwkru_H7IuWJ3A74y5mINU2p7Ek',
    appId: '1:761135292455:web:2f757ad0a7887cf83e6e02',
    messagingSenderId: '761135292455',
    projectId: 'rseed-770db',
    authDomain: 'rseed-770db.firebaseapp.com',
    storageBucket: 'rseed-770db.firebasestorage.app',
  );
}
